apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-storage
  namespace: monitoring
  labels:
    type: nfs
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /grafana-persistant-volume
